"""add connection_info to worlds

Revision ID: 98c734c18da7
Revises: 5d46be5c7038
Create Date: 2026-08-17 21:24:21.629488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98c734c18da7'
down_revision: Union[str, Sequence[str], None] = '5d46be5c7038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('connection_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'connection_info')
    # ### end Alembic commands ###
